### PR TITLE
fix(tooltip): Correct condition of making tooltip text

### PR DESCRIPTION
**Pull request by soyme**
## Issue
#940

## Details
Update condition when generate the beginning of tooltip text.

### CODE REVIEW

**Comment by netil** [comment]
@soyme, can you add test code?

**Comment by netil** [comment]
@soyme, I added test code for this. Please consider adding it for next PR.
Anyway, thanks for the contribution!

**Comment by soyme** [comment]
@netil Thank you very much for quick support!

**Pull request closed without merging**
