### PR TITLE
feat(types): Add area-step-range chart type

### PR DESCRIPTION
**Pull request by vlaforet**
## Details
This PR adds the area-step-range chart type. This new type is part of the AreaRange and Step categories which makes a stepped range.
No new code needed to be added apart from adding the type and its categories.

### CODE REVIEW

**Comment by netil** [comment]
Hi @vlaforet, thanks for the contribution!
I'll review soon.

**Comment by vlaforet** [comment]
Fixed a bug that prevented onClick on area-step-range charts.
Onclick calls isWithinShape which calls isWithinStep with the return value of the scale function. The scale function expects the point value as parameter. This value is a number for "step" charts but it is an array of mid, low, high in "area-step-range".
I changed the call to the scale function to take the base value of the point (returned by getBaseValue(d)).

**Comment by netil** [comment]
@vlaforet mostly nice implementing to use current existing condition without adding extra code.
Could you add test code?

**Comment by vlaforet** [comment]
Thanks!
Yes sure. I will work on tests this week.

**Comment by netil** [comment]
@vlaforet added test codes and demos. 
Thanks again for the contribution!

**Comment by vlaforet** [comment]
Nice, thank you!
I had not been able to get to it.

**Pull request closed without merging**
