### PR TITLE
feat(bubble): expand bubble chart feature with plugin

### PR DESCRIPTION
**Pull request by jm-chong**
- set bubble min/max radius, focus expand scale
- implement new feature with plugin

## Issue
none

## Details
improve bubble chart feature
- specify min / max radius
- focus bubble when mouse over
- override internal functions using plugin hook.
- added demo page & test code

### CODE REVIEW

**Comment by netil** [comment]
Hi @jm-chong, great work!
Can you add documentation & type definition?

Take as ref. from other plugins:
- API doc: https://naver.github.io/billboard.js/release/latest/doc/plugin-stanford.html
- TS definition: https://github.com/naver/billboard.js/tree/master/types/plugin

**Comment by jm-chong** [comment]
Okay. I just added documentation and type definition.
If I missed any other things, please let me know.

**Comment by netil** [comment]
@jm-chong, just merged with some format & description updates.
Thanks again for the contribution!

**Pull request closed without merging**
