### PR TITLE
feat(alternate-markers): Implement alternate markers feature

### PR DESCRIPTION
**Pull request by julien**
## Issue

#202 

## Details

Solution for alternate markers feature.

### CODE REVIEW

**Comment by netil** [comment]
Hi @julien. I was thinking how to simplify the usage of the custom data point.
Letting user to define 2 functions(create, update) is not really easy approach.

Thinking that in most custom data point can be interpreted using `<polygon>`.
The problematic of the previous PR was the difficulty on positioning the element, but I found that defining `<polygon>` as part of `<defs>` meber, and using `<use>` can make to be positioned using x/y attributes.

- https://developer.mozilla.org/ko/docs/Web/SVG/Element/use

```html
<defs>
     ...
     <polygon points="..." id="somethingPoint">
</defs>

<g class=" bb-shapes bb-shapes-data1 bb-circles bb-circles-data1">
    <use x="50" y="30" href="#somethingPoint" />
     ...
</g>

```

And finally the interface can be simplified as below.
Like 'diamond' and 'triangle' can be added as the one of the default types.
If user wants add some specific type, just pass a reference of the `<polygon>` element created.

```js
point: {
     pattern: [
          "rectangle",
          "diamond",
          <polygon>
     ]
}
```

What do you think about?

**Comment by julien** [comment]
Hey @netil,

This sounds like a good idea, simplifying things is always good INMHO.

I'll have a look into it and get back to you shortly.

Thanks!

**Comment by netil** [comment]
Great @julien, let me know if you need some help :)

**Comment by julien** [comment]
Hi again @netil,  

I'm trying to implement this as suggested, but it seems that with the `use` element, things behave a bit differently.

- The first thing is that we need to "copy" the custom point into the chart's `defs` element (like with the tiles), and if this "point" is repeated there is no easy way to assign it a unique id (which leads to duplicated id's in the document later on)

 - There's also a difference when using `use` compared to using a `circle`, `rectangle` or `polygon` directly because `use` uses Shadow DOM.

use-shadow-dom

- With `use` when resizing the window in which the chart is rendered, new elements get created instead of being updated like with the other shapes.

I've pushed my changes if you'd like to test this locally.
If you have time, I'd appreciate you help.

Thanks!

**Comment by julien** [comment]
@netil ,

I wanted to give you a quick update concerning my last comment:

The bug that was causing elements to be duplicated has been fixed, it's probably because I wasn't setting their `class` attribute in my previous PR.

The only issue I'm facing now is positioning these elements when they are selected via `mouseover`, maybe you have an idea on how to fix this.

Thanks!

**Comment by netil** [comment]
@julien great! I'll look for that.

**Comment by netil** [comment]
I was digging with `<use>`, but there're side effects on using it.
And also the current PR has problem not functioning well with different APIs (like .flow()).

Let me try to find out the best way to simplify the usage without breaking the compatibility.

**Comment by julien** [comment]
@netil ,

Thanks for the details.

As a side note, I think we should maybe try to forget https://github.com/naver/billboard.js/issues/173 and https://github.com/naver/billboard.js/pull/184:

Being able to draw different shapes is only meaningfull when showing several datasets (to be able to distinguish them more easily), so maybe we should only focus on one way to do it. (And not allow defining custom "points" with `{create(){}, update(){}}` Objects)

Since this is still work in progress I don't think there's any  risk of breaking the existing API. What do you think?

Thanks

**Comment by netil** [comment]
@julien 

Well, just speaking, this feature can be really useful in many ways, but in terms of implementation, always needs to taking care of the existing features and the incompatibility.

Implementing custom data point not ends in just rendering. It should consider all the existing behaviors(like when mouseover happens, it should change the scale, etc.) of the data points and the harmony with others APIs and so on.

So, it should be treated very carefully not affecting others. I think data point is one of those `picky` implementation.

There's no many times left until the next release, so I'll try to look for couple more days on it. 
If I can't find the proper way, it can be postponed for the next release.

Thanks anyway for the concerns and thanks for the continuous contribution!

**Comment by julien** [comment]
@netil ,

I have a solution for the `transform` issue.
Could you tell me what the issue with the `flow` API is exactly?

Thanks

**Pull request closed without merging**
