### PR TITLE
docs(demo): Updated JSON key without quotes in demo

### PR DESCRIPTION
**Pull request by haracejacob**
## Issue

None

## Details

In the example of the demo page(https://naver.github.io/billboard.js/demo/), I think that double quotes in the key part of JSON hurt readability.
I added <code>.replace(/\"([^(\")"]+)\":/g,"$1:")</code> to JSON.stringify()
This regular expression changes the "key" : "value" to key : "value"

### CODE REVIEW

**Comment by netil** [comment]
@haracejacob good job!
Could you update your commit log to follow our commit guideline?
- https://github.com/naver/billboard.js/blob/master/CONTRIBUTING.md#commit-log-guidelines

**Comment by haracejacob** [comment]
했는데 한번 검토 가능하신가요?

**Comment by netil** [comment]
Hmm... it doesn't meet the guideline.

BTW, all the communications in this project, are done in english.
So, try to communicate in english rather than korean.

**Comment by haracejacob** [comment]
I have changed Korean to English. And added module name in header.
Can you check it once?
If this doesn't meet the guideline. Let me know.

**Comment by netil** [comment]
@haracejacob sorry to be delayed on reviewing.

There're few changes needed.

- I think, the regex just pointing word will be okay.
 ```js
// your code
.replace(/"([^(")"]+)":/g,"$1:")

// just simply
// '\w' is equivalent as [0-9A-Za-z_]
.replace(/"(\w+)":/g,"$1:")
```

- The replace position should be changed.
  From your change, it doesn't cover all. Replacement should happen in different level.
```js
var codeStr = "var chart = bb.generate("+
	...
	} else if (/(columns|rows|json)/.test(key)) {
		...
		.replace(/"([^(")"]+)":/g,"$1:");  // <-- your code replacement
			
		return key === "json" ?
			str.replace(/{/, "{\r\n\t").replace(/}/, "\r\n    }") : str;
	}

	return value;
}, 2)
...
.replace(/"(\w+)":/g,"$1:")  // <-- replacement should happened at this level
.replace(/\\n(?!T)/g, "\n") +");";
```

**Comment by haracejacob** [comment]
OK, i fixed. Could you check again?

**Pull request merged**
