### PR TITLE
chore(release): integrate semantic-release

### LINKED ISSUE #893: Semantic-release integration
Hey! Based on [our recent conversation](https://github.com/naver/billboard.js/issues/863#issuecomment-490337157), you seem like you might be open to a PR the integrates [semantic-release](https://github.com/semantic-release/semantic-release) to help you ship code more frequently and with fewer manual steps. Before I get too deep in the integration, I wanted to make sure this is something that would help you + the billboard.js community. 

If you're up for considering it, I think the best general approach would be:
- two distribution channels, `current` and `nightly` mapping to the branches:
  - `master` -> `current`
  - `nightly` -> `nightly`
- `current` will be released as it currently is
- `nightly` will be released as a [pre-release](https://github.com/semantic-release/evolution/blob/release-workflows/_drafts/release-workflows.md#pre-releases) with a name like `billboard.js@1.8.1-nightly.1` instead of the timestamp
  - I'd also consider changing `nightly` to `next` (and publishing with the `@next` tag) 
- using semantic-release's [changelog plugin ](https://github.com/semantic-release/changelog) to generate the changelog from the commits
- using semantic-release's [release-notes plugin ](https://github.com/semantic-release/release-notes-generator)to generate the release info from the changelog
- publish releases to [`npm`](https://github.com/semantic-release/npm) and to [`github`](https://github.com/semantic-release/github) 
- and, of course, still publish gh-pages from `master`

PR flow would then have to be: new code -> `nightly` -> `master`, if you're ok with that.

Again, I'm up for making all these changes - just want to get your feedback before really starting, but I think it could make your life a bit easier!

### PR DESCRIPTION
**Pull request by austince**
## Issue

I haven't tried integrating semantic release with a project with as complex of a release process as `billboard` before, so please let me know if I've missed something and if this will work for you + the community! 

Ref #893 

## Details

Integrates `semantic-release` for releasing and changelog generation.

For this to work, we will still have to:
- [ ] make a `next` branch off of `master`
- [x] add a [`GH_TOKEN`](https://github.com/semantic-release/github#configuration) and an [`NPM_TOKEN`](https://github.com/semantic-release/npm#environment-variables) to the Travis CI environment (if not already present)

### Releasing

Initially sets up two release channels, `latest` and `next`, [following their guidelines,](https://github.com/semantic-release/evolution/blob/release-workflows/_drafts/release-workflows.md#future-branches) - `latest` tracks `master` and `next` tracks `next`. `next` should allow us to intervene before releases reach the majority of users. Once `next` is set up, we can move the base of this PR to it, which should provide some time for intervention / a buffer from releasing on the main channel if something needs to be tweaked.

Documentation pushed to GitHub pages with the `config/deploy.sh` script will now similarly publish to `release/latest` from `master` and `release/next` from `next`.

#### Workflow

In order to keep channels compatible, `master` will only accept `fix` and `feat` commits and `next` will accept all others.
 
new code -> `next` (when features/fixes ready to release) -> `master`

Breaking changes will have to have `BREAKING CHANGE` in the commit footer when pushed to `master`.

### Changelog / Commit conventions
Switches over to using [`conventional-changelog`'s `commitlint`](https://github.com/conventional-changelog/commitlint) for commit message validation, customized to the [Naver](https://github.com/naver/billboard.js/blob/master/CONTRIBUTING.md#commit-log-guidelines) guidelines. The guidelines were very close to the [standard conventions](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md), so customization fit well. `semantic-release`'s [commit analyzer](https://github.com/semantic-release/commit-analyzer) uses conventional changelog, so better to be in line with that. There are [plenty more configuration rules](https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md) we could add if you want! 

I also noticed that `husky` was already being used, so I added commit linting to the commit hook.

### Semantic Release Plugins Used

- [`commit-analyzer`](https://github.com/semantic-release/commit-analyzer) to determine the next version from commit messages.
- [`release-notes-generator`](https://github.com/semantic-release/release-notes-generator) to summarize the release.
- [`changelog`](https://github.com/semantic-release/changelog) to update the CHANGELOG.md file.
- [`github`](https://github.com/semantic-release/github) to publish a [GitHub release](https://github.com/chaijs/chai-http/releases).
- [`git`](https://github.com/semantic-release/git) to commit release assets + a tag.
- [`npm`](https://github.com/semantic-release/npm) to publish to [npm](https://www.npmjs.com/package/billboard.js).

Closes #893 
P.S. the massive diff is mostly the lock files!

### CODE REVIEW

**Comment by netil** [comment]
@austince, great work! 😃 
I'll be start taking time on reviewing~

**Comment by netil** [comment]
@austince, sorry for the delays. It's taking time on reviewing this due to the next release schedule approaches.

I'm not sure this release flow to be used on this coming or for the next release, but I'll be trying to look ASAP.

**Comment by austince** [comment]
@netil, no worries! It's a major change and I'm up for making adjustments to it if you find it's not quite right - take your time!

**Comment by netil** [comment]
@austince, thanks for the contribution again!
I just merge with some changes. 

In order to have control over the timing of releases, added `dev` branch.
- [Triggering a release](https://semantic-release.gitbook.io/semantic-release/#triggering-a-release)

## Branches

- master: latest tag
- next: next tag
- dev: primary branch
   Will takeover previous master branch's role.


## Workflow

1. All devs will be done on `dev`.
   `nightly` will merge changes from `dev` and build `nightly dist` every day.

2. At the time of RC release:
    `dev` will be merged into `next` branch
    Every updates before the latest, should flows from `dev` to `next`.

    > Will publish @next by semantic-release

3. At the time of latest(stable) release:
    `next` will be merged into `master` branch.

    > Will publish @latest by semantic-release

**Comment by austince** [comment]
@netil awesome, thanks for the collaboration and hope this helps with the maintenance burden! Looking forward to what comes next.

**Comment by austince** [comment]
We might also consider using [pre-releases](https://github.com/semantic-release/semantic-release/issues/563) instead of the nightly builds when they make it out of beta, so every commit is available for testing.

**Comment by netil** [comment]
@austince, `branches` option is part of the beta. So I don't know when stable will come, but when it comes(or make to use beta for now) below config will be applied.
> [Configuration doc](https://github.com/semantic-release/semantic-release/blob/beta/docs/usage/configuration.md#branches)

```js
  // releaserc.json
  "branches": [
    "master",
    {"name": "next", "prerelease": true},
    {"name": "nightly", "prerelease": true}
  ]
```

**Pull request closed without merging**
