### PR TITLE
feat: Stanford Diagrams

### PR DESCRIPTION
**Pull request by FreezinG117**
Add support for [Stanford Diagrams](https://gssc.esa.int/navipedia/index.php/The_Stanford_%E2%80%93_ESA_Integrity_Diagram:_Focusing_on_SBAS_Integrity).

### CODE REVIEW

**Comment by netil** [comment]
Hi @FreezinG117, thanks for the awesome 👍 💯 PR.
I'll be taking time for reviewing this.

**Comment by netil** [comment]
@FreezinG117, sorry for the delays. I'll be shortly describing what I'm planning for.

After the review, the `stanford diagram` is a great feature, but I figured out 2 main concerns on this.

- Wondering on its generalized usage, because of its nature.
  > **Stanford Diagram is:**
  > Integrity-Availability-Accuracy 2D histogram based on Satellite Based Augmentation Systems(SBAS). Shows the relationship of position errors against protection levels for a set of measurements using an all in view satellite selection.
- Adding as a basic library feature, will increment the final bundle size
  > Will increment approx. 10kb on minfied version, which means for every user will be impacted for this.

Hence, I'm on planning to add as part of `plugin`.
Plugin is one of the [planned feature](https://github.com/naver/billboard.js/wiki/Roadmap#support-of-extensionplugin-system), and they're also requested by the users(#586, #701).

I'm on working for the interface & the structure(build, etc.) for that.
So, please hang tight till finishing and the re-structured plugin version of `Stanford diagram`.

Thanks 😃

**Comment by netil** [comment]
@FreezinG117, just merged to master.
Took time on adding plugin interface & re-structuring stanford as new plugin interface.

Thanks for the contribution again!

**Comment by FreezinG117** [comment]
Hi@netil Thanks for your work.

Do you have an ETA for the release in npm?

**Comment by netil** [comment]
The next regular release schedule can be found at:
- https://github.com/naver/billboard.js/milestone/12

You can try `nightly` before the official release.
- https://github.com/naver/billboard.js/tree/nightly/dist

**Pull request closed without merging**
