### PR TITLE
feat(axis): Clone y/y2-axis domain if no data is bound to one of them

### PR DESCRIPTION
**Pull request by michkami**
## Issue
#1231 

## Details
As described in #1231

### CODE REVIEW

**Comment by netil** [comment]
thanks @michkami for the contribution!

**Comment by netil** [comment]
Seems having a side-effect. Checking out the follow example, 
- https://naver.github.io/billboard.js/demo/#Tooltip.TooltipFormat

Toggling data shouldn't be affecting axis updates, because each data is bound to y and y2 respectively. But when toggling the data, it's axis bound wrongly as follow screenshot.

data-y-axes

The expected one is:
data-y-axes-expected

**Comment by michkami** [comment]
It seems like updating  y/y2 axis domain is still necessary in case when the difference between the shown data max value and the hidden data max value is big enough.

The bug you are describing is my fault, because my code doesn't check, if data is bound to multiple axes.
There are 3 cases that have to be checked:
1. All data is bound to y
    - Here the domain of y2 clones y domain
2. All data is bound to y2
    - Here the domain of y clones y2 domain
3. Some data is bound to y and some to y2
    - In this case the domains won't be cloned, because there are values bound to all axes.

By changing [this condition](https://github.com/naver/billboard.js/blob/master/src/internals/domain.js#L81) to the code at the bottom it should work properly.

One more question: Would it make sense to also clone the formatting of the cloned axis?
In you look at the first case in the examples below, y2 axis clones y axis domain, but it still uses its own formatting.
Are there any cases where it would make sense to use 2 different formats for same value?

Should I make a pull request for this change @netil ?

### Examples
**2 Columns:**
- All data bound to y  axis
y_axis

- All data bound to y2  axis
y2_axis

- data1 bound to y axis, data2 bound to y2 axis
multiple_axis

**3 Columns:**
- All data bound to y  axis
y_axis

- All data bound to y2  axis
y2_axis

- data1 and data3 bound to y axis, data2 bound to y2 axis
multiple_axes

### Code

``` javascript
if (yTargets.length === 0) { // use domain of the other axis if target of axisId is none
	const dataAxes = Object.values(config.data_axes);
	const dataAxesContainsOnlyOneAxis = dataAxes.every((val, i, arr) => val === arr[0]);
	const dataBoundToOneAxis = dataAxes.length === 0 ||
		(dataAxesContainsOnlyOneAxis && dataAxes[0] !== "y2") ||
		(dataAxesContainsOnlyOneAxis && ($$.data.targets.length === dataAxes.length));

	if (dataBoundToOneAxis) {
		if (axisId === "y2") {
			// When all data bounds to y, y2 Axis domain should clone y domain.
			return $$.y.domain();
		} else {
			// When all data bounds to y2, y Axis domain should clone y2 domain.
			// So, it needs to call to get y2 domain here
			return this.getYDomain(targets, "y2", xDomain);
		}
	} else {
		// When data is bound to multiple axes it should not clone the domain.
		return $$[axisId].domain();
	}
}
```

**Comment by netil** [comment]
@michkami thanks for the detailed lookups.

> 3. Some data is bound to y and some to y2
This case is only when data has different axis bounds.

> One more question: Would it make sense to also clone the formatting of the cloned axis?
> In you look at the first case in the examples below, y2 axis clones y axis domain, but it still uses its own formatting.

No, it shouldn't. The corresponding axis should use own `tick.format` options value, because applying those not visible convention, will make harder maintain.

> Are there any cases where it would make sense to use 2 different formats for same value?

I can't say is usual, but I can't eliminate the possible use cases.

> Should I make a pull request for this change @netil ?

I'll try fix this, but If I need, I'll ask for your help 😄

**Pull request closed without merging**
